server:
  port: 3000
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://192.168.25.132:5432/activiti?seUnicode=true;characterEncoding=UTF-8
    username: pg01
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
